secure-doc.urls=https://secure-doc.store,https://www.secure-doc.store,\
    https://secure-doc.cloud,https://www.secure-doc.cloud,\
    https://secure.doc.store,https://www.secure.doc.store,\
    https://imagey.app,https://www.imagey.app,\
    https://imagey.cloud,https://www.imagey.cloud,\
    https://imagey.org,https://www.imagey.org

mail.invitation.subject=Invitation to %s
mail.invitation.body=You are invited to %s by %s: To accept the invitation, click <a href="%s">here</a>

mail.login.subject=Sign in to %s
mail.login.body=Please click the link to sign in to %s: <a href="%s">Sign in</a>

mail.registration.subject=Email Verification for %s
mail.registration.body=Please verify your email address to register to %s by clicking the following link: <a href="%s">Register</a>
