secure-doc.urls=https://secure-doc.store,https://www.secure-doc.store,\
    https://secure-doc.cloud,https://www.secure-doc.cloud,\
    https://secure.doc.store,https://www.secure.doc.store,\
    https://imagey.app,https://www.imagey.app,\
    https://imagey.cloud,https://www.imagey.cloud,\
    https://imagey.org,https://www.imagey.org
